# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='compare',
        ),
    ]
