# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_auto_20160528_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='avg_length1',
            field=models.FloatField(default=0, help_text='Average Length of tweets with hashtag1, - Bigger is WINNER'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='frequency1',
            field=models.FloatField(default=0, help_text='Frequency of tweets with hashtag1 (number of tweets per minute), - Bigger is WINNER'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='num_typo1',
            field=models.IntegerField(default=0, help_text='Number of typos in tweets with hashtag1, - Smaller is WINNER'),
        ),
    ]
