# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20160529_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='compare',
            field=models.CharField(choices=[('Number of typos', 'Number of typos'), ('Length of tweets', 'Length of tweets'), ('Frequency of tweets', 'Frequency of tweets')], default='Number of typos', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
